return {
	chicken_dodo2 = {
		acceleration = 6,
		activatewhenbuilt = true,
		autoheal = 135,
		brakerate = 0.2,
		buildcostenergy = 9000,
		buildcostmetal = 350,
		builder = false,
		buildpic = "CHICKEN_DODO2.DDS",
		buildtime = 15000,
		canguard = true,
		canhover = "1",
		canmove = true,
		canpatrol = true,
		canstop = "1",
		category = "MOBILE WEAPON NOTAIR NOTSUB NOTSHIP NOTHOVER ALL SURFACE",
		collide = 0,
		collisionvolumeoffsets = "0 3 0",
		collisionvolumescales = "18 28 41",
		collisionvolumetype = "box",
		corpse = "DEAD",
		description = "Chicken Bomb",
		explodeas = "DODO_DEATH2",
		floater = false,
		footprintx = 1,
		footprintz = 1,
		hidedamage = 1,
		icontype = "chicken",
		kamikaze = true,
		kamikazedistance = 72,
		leavetracks = true,
		maneuverleashlength = "640",
		mass = 10000,
		maxdamage = 1350,
		maxslope = 18,
		maxvelocity = 8,
		maxwaterdepth = 0,
		movementclass = "CHICKENHOVERDODO",
		name = "Alpha Dodo",
		noautofire = false,
		nochasecategory = "VTOL SINK HOVER",
		objectname = "big_chicken_dodo.s3o",
		seismicsignature = 4,
		selfdestructas = "DODO_DEATH2",
		selfdestructcountdown = 0,
		sightdistance = 100,
		stealth = 1,
		trackoffset = 1,
		trackstrength = 6,
		trackstretch = 1,
		tracktype = "ChickenTrack",
		trackwidth = 10,
		turninplace = 0,
		turnrate = 1000,
		upright = false,
		waterline = 1,
		workertime = 0,
		customparams = {
			faction = "chicken",
			normalmaps = "yes",
			normaltex = "unittextures/chicken_normal.tga",
		},
		featuredefs = {
			dead = {},
			heap = {},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:DODOTRAIL",
				[2] = "custom:blood_explode",
				[3] = "custom:dirt",
			},
		},
	},
}
