return {
	chickenc2 = {
		acceleration = 1.25,
		brakerate = 2,
		buildcostenergy = 5280,
		buildcostmetal = 170,
		builder = false,
		buildpic = "CHICKENC2.DDS",
		buildtime = 15000,
		canattack = true,
		canguard = true,
		canmove = true,
		canpatrol = true,
		canstop = "1",
		category = "MOBILE WEAPON NOTAIR NOTSUB NOTSHIP ALL NOTHOVER SURFACE",
		collisionvolumeoffsets = "0 11 3",
		collisionvolumescales = "25 38 64",
		collisionvolumetype = "box",
		corpse = "DEAD",
		description = "All-Terrain Assault",
		explodeas = "BIGBUG_DEATH",
		footprintx = 3,
		footprintz = 3,
		icontype = "chickenr",
		leavetracks = true,
		maneuverleashlength = "640",
		mass = 900,
		maxdamage = 10000,
		maxslope = 18,
		maxvelocity = 4.25,
		maxwaterdepth = 15,
		movementclass = "TKBOT3",
		name = "Manticore",
		noautofire = false,
		nochasecategory = "VTOL",
		objectname = "chickenc2.s3o",
		seismicsignature = 3,
		selfdestructas = "BIGBUG_DEATH",
		sightdistance = 512,
		sonardistance = 450,
		trackoffset = 0.5,
		trackstrength = 9,
		trackstretch = 1,
		tracktype = "ChickenTrackPointy",
		trackwidth = 70,
		turninplace = 0,
		turnrate = 1200,
		upright = false,
		workertime = 0,
		customparams = {
			faction = "chicken",
			normalmaps = "yes",
			normaltex = "unittextures/chicken_normal.tga",
		},
		featuredefs = {
			dead = {},
			heap = {},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:blood_spray",
				[2] = "custom:blood_explode",
				[3] = "custom:dirt",
			},
		},
		weapondefs = {
			weapon = {
				accuracy = 128,
				areaofeffect = 160,
				avoidfeature = 0,
				camerashake = 0,
				cegtag = "ROCKTRAILsm",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:gundam_MISSILE_EXPLOSION",
				impulseboost = 0.22,
				impulsefactor = 0.22,
				intensity = 0.7,
				interceptedbyshieldtype = 1,
				model = "SGreyRock1.S3O",
				name = "Blob",
				noselfdamage = true,
				range = 350,
				reloadtime = 1.8,
				rgbcolor = "0.0 0.6 0.6",
				size = 8,
				sizedecay = -0.3,
				soundhit = "xplomed2",
				sprayangle = 256,
				targetmoveerror = 0.2,
				tolerance = 5000,
				turret = true,
				weapontimer = 0.2,
				weaponvelocity = 500,
				damage = {
					default = 1300,
				},
			},
		},
		weapons = {
			[1] = {
				def = "WEAPON",
				maindir = "0 0 1",
				maxangledif = 110,
			},
		},
	},
}
