return {
	chicken_dodo1 = {
		acceleration = 6,
		activatewhenbuilt = true,
		autoheal = 50,
		brakerate = 0.2,
		buildcostenergy = 3000,
		buildcostmetal = 128,
		builder = false,
		buildpic = "CHICKEN_DODO1.DDS",
		buildtime = 3000,
		canguard = true,
		canhover = "1",
		canmove = true,
		canpatrol = true,
		canstop = "1",
		category = "MOBILE WEAPON NOTAIR NOTSUB NOTSHIP NOTHOVER ALL SURFACE",
		collide = false,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "10 14 22",
		collisionvolumetype = "box",
		corpse = "DEAD",
		description = "Chicken Bomb",
		explodeas = "DODO_DEATH1",
		floater = false,
		footprintx = 1,
		footprintz = 1,
		hidedamage = 1,
		icontype = "chicken",
		kamikaze = true,
		kamikazedistance = 40,
		leavetracks = true,
		maneuverleashlength = "640",
		mass = 5000,
		maxdamage = 200,
		maxslope = 18,
		maxvelocity = 7,
		maxwaterdepth = 0,
		movementclass = "CHICKENHOVERDODO",
		name = "Dodo",
		noautofire = false,
		nochasecategory = "VTOL SINK HOVER",
		objectname = "chicken_dodo.s3o",
		seismicsignature = 2,
		selfdestructas = "DODO_DEATH1",
		selfdestructcountdown = 0,
		sightdistance = 36,
		stealth = 1,
		trackoffset = 1,
		trackstrength = 6,
		trackstretch = 1,
		tracktype = "ChickenTrack",
		trackwidth = 10,
		turninplace = 0,
		turnrate = 2000,
		upright = false,
		waterline = 1,
		workertime = 0,
		customparams = {
			faction = "chicken",
			normalmaps = "yes",
			normaltex = "unittextures/chicken_normal.tga",
		},
		featuredefs = {
			dead = {},
			heap = {},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:blood_spray",
				[2] = "custom:blood_explode",
				[3] = "custom:dirt",
			},
		},
	},
}
