return {
	corcsa = {
		acceleration = 0.071999996900558,
		brakerate = 0.4275,
		buildcostenergy = 24047,
		buildcostmetal = 256,
		builddistance = 136,
		builder = true,
		buildpic = "CORCSA.DDS",
		buildtime = 20904,
		canfly = true,
		canmove = true,
		cansubmerge = true,
		category = "ALL NOTLAND MOBILE NOTSUB ANTIFLAME ANTIEMG ANTILASER VTOL NOWEAPON NOTSHIP NOTHOVER",
		collide = false,
		cruisealt = 55,
		description = "Level 2 Construction Seaplane",
		energymake = 20,
		energystorage = 75,
		energyuse = 20,
		explodeas = "CA_EX",
		footprintx = 2,
		footprintz = 2,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5 ,
		idletime = 1800 ,
		maxdamage = 390,
		maxslope = 10,
		maxvelocity = 8.5100002288818,
		maxwaterdepth = 255,
		metalmake = 0.20000000298023,
		metalstorage = 75,
		name = "Construction Seaplane",
		objectname = "CORCSA.s3o",
		radardistance = 50,
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT_AIR",
		sightdistance = 351,
		terraformspeed = 300,
		turninplaceanglelimit = 360,
		turnrate = 132,
		workertime = 110,
		buildoptions = {
			[1] = "corap",
			[2] = "coraap",
			[3] = "corfmine3",
			[4] = "coruwadves",
			[5] = "coruwadvms",
			[6] = "coruwfus",
			[7] = "coruwmme",
			[8] = "coruwmmm",
			[9] = "corfatf",
		},
		customparams = {
			normalmaps = "yes",
			normaltex = "unittextures/Core_normal.dds",
		},
		sounds = {
			build = "nanlath1",
			canceldestruct = "cancel2",
			repair = "repair1",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
				},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "seapsel2",
			},
		},
	},
}
