 return {
 ["dust_cloud"] = {
    poof01 = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.93,
        alwaysvisible      = false,
        colormap           = [[0.25 0.20 0.10 0.5	0 0 0 0.00]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 25,
        emitvector         = [[0, 0, 0]],
        gravity            = [[r-0.05 r0.05, 0 r0.05, r-0.05 r0.05]],
        numparticles       = 2,
        particlelife       = 3,
        particlelifespread = 22,
        particlesize       = 12,
        particlesizespread = 1.1,
        particlespeed      = 3,
        particlespeedspread = 10,
        pos                = [[r-3 r3, 1, r-3 r3]],
        sizegrowth         = [[r0.20 r0.30]],
        sizemod            = 1.0,
        texture            = [[dirt]],
      },
    },
  },
  ["dust_cloud_fast"] = {
    poof01 = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      properties = {
        airdrag            = 0.90,
        alwaysvisible      = false,
        colormap           = [[0.25 0.20 0.10 0.45 0 0 0 0.00]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 25,
        emitvector         = [[0, 0, 0]],
        gravity            = [[r-0.05 r0.05, 0 r0.09, r-0.05 r0.05]],
        numparticles       = 2,
        particlelife       = 3,
        particlelifespread = 26,
        particlesize       = 8,
        particlesizespread = 3,
        particlespeed      = 3,
        particlespeedspread = 10,
        pos                = [[r-3 r3, 1, r-3 r3]],
        sizegrowth         = [[r0.25 r0.40]],
        sizemod            = 1.0,
        texture            = [[dirt]],
      },
    },
  }, 
}
