local tracks = {
	peace = {
		{title = "Professor Kliq - Lucio's Smoke Jacket (feat. Lucio Oquendo)", filename = "ProfessorKliq-LuciosSmokeJacket.ogg"},
		{title = "Professor Kliq - Bad News Ain't Good News To Me" , filename = "ProfessorKliq-BadNewsAintNewsToMe.ogg"},
		{title = "Professor Kliq - The New Industry"               , filename = "ProfessorKliq-TheNewIndustry.ogg"},
		{title = "Professor Kliq - You Have Been Chosen"           , filename = "ProfessorKliq-YouHaveBeenChosen.ogg"},
		{title = "THA - Empty Chasms"                              , filename = "THA-emptychasms.ogg"},
		{title = "THA - Reveal"                                    , filename = "THA-reveal.ogg"},
		{title = "THA - Murder Taxi"                               , filename = "THA-murdertaxi.ogg"},
		{title = "Clearside - Virus"                               , filename = "Clearside-Virus.ogg"},
		{title = "ToneScape - Displexia"                           , filename = "ToneScape-Displexia.ogg"},
		{title = "Turning Point - Whatever"                        , filename = "TurningPoint-Whatever.ogg"},
		{title = "Duane Naulls - Distant Cry"                      , filename = "DuaneNaulls-DistantCry.ogg"},
		{title = "Vicenzo Bosa - Eyes of Revelation"               , filename = "VicenzoBosa-EyesOfRevelation.ogg"},
		{title = "Szymon Matuszewski - Crispy Town"                , filename = "SzymonMatuszewski-CrispyTown.ogg"},
		{title = "Szymon Matuszewski - Birthday"                   , filename = "SzymonMatuszewski-Birthday.ogg"},
		{title = "Szymon Matuszewski - Borealis"                   , filename = "SzymonMatuszewski-Borealis.ogg"},
	},
	coldWar = {
		{title = "THA - Sandcrab Riders"                , filename = "THA-sandcrabriders.ogg"},
		{title = "THA - The Overseer"                   , filename = "THA-theoverseer.ogg"},
		{title = "THA - The Solution"                   , filename = "THA-thesolution.ogg"},
		{title = "Clearside - Shape Shifter"            , filename = "Clearside-Shapeshifter.ogg"},
		{title = "Mateusz Morawski - Tehenon Milestone" , filename = "MateuszMorawski-TehenonMilestone.ogg"},
		{title = "Professor Kliq - Tension Growl"       , filename = "ProfessorKliq-TensionGrowl.ogg"},
		{title = "Rob Richert - Alias Zero"             , filename = "RobRichert-AliasZero.ogg"},
	},
	war = {
		{title = "ClearSide - Sandblaster"           , filename = "Clearside-Sandblaster .ogg"},
		{title = "ClearSide - Shape Shifted"         , filename = "Clearside-ShapeShifted.ogg"},
		{title = "ClearSide - Siste Viator"          , filename = "Clearside-SisteViator.ogg"},
		{title = "ClearSide - Surveillance"          , filename = "Clearside-Surveillance.ogg"},
		{title = "ClearSide - Through My Mind"       , filename = "Clearside-ThroughMyMind.ogg"},
		{title = "Mateusz Morawski - Branmorph"      , filename = "MateuszMorawski-Branmorph.ogg"},
		{title = "Mateusz Morawski - Eightmar"       , filename = "MateuszMorawski-Eightmar.ogg"},
		{title = "Mateusz Morawski - Lectrosuite"    , filename = "MateuszMorawski-Lectrosuite.ogg"},
		{title = "Mateusz Morawski - Pursuit"        , filename = "MateuszMorawski-Pursuit.ogg"},
		{title = "Professor Kliq - I'll Go Rhythm"   , filename = "ProfessorKliq-IllGoRhythm.ogg"},
		{title = "THA - Materializing Cats in Space" , filename = "THA-materializingcatsinspace.ogg"},
		{title = "THA - The Collapse"                , filename = "THA-thecollapse.ogg"},
	},
}

return tracks