return {
	armfdrag = {
		acceleration = 0,
		blocking = true,
		brakerate = 0,
		buildangle = 8192,
		buildcostenergy = 640,
		buildcostmetal = 21,
		buildpic = "ARMFDRAG.DDS",
		buildtime = 930,
		canattack = false,
		canrepeat = false,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
		crushresistance = 250,
		description = "Light Wall",
		footprintx = 2,
		footprintz = 2,
		hidedamage = true,
		idleautoheal = 0,
		maxdamage = 15000,
		maxslope = 32,
		minwaterdepth = 1,
		name = "Shark's Teeth",
		objectname = "ARMFDRAG.s3o",
		repairable = false,
		seismicsignature = 0,
		sightdistance = 1,
		waterline = 0,
		yardmap = "wwww",
		customparams = {
			faction = "arm",
		},
	},
}
