return {
	armfdrag = {
		acceleration = 0,
		brakerate = 0,
		buildangle = 8192,
		buildcostenergy = 600,
		buildcostmetal = 20,
		buildpic = "ARMFDRAG.DDS",
		buildtime = 930,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
		corpse = "FLOATINGTEETH",
		description = "Perimeter Barrier"
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 5,
		idletime = 1800,
		isfeature = true,
		maxdamage = 50,
		maxslope = 32,
		minwaterdepth = 1,
		name = "Shark's Teeth",
		objectname = "ARMFDRAG.s3o",
		seismicsignature = 0,
		sightdistance = 130,
		waterline = 0,
		yardmap = "wwww",
		featuredefs = {
			floatingteeth = {
				autoreclaimable = 0,
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -35 0",
				collisionvolumescales = "37 70 37",
				collisionvolumetest = 1,
				collisionvolumetype = "box",
				damage = 15000,
				description = "Shark's Teeth",
				floating = true,
				footprintx = 2,
				footprintz = 2,
				height = 75,
				hitdensity = 100,
				metal = 20,
				nodrawundergray = true,
				object = "armfdrag.s3o",
				reclaimable = true,
				upright=true,
				world = "allworld",
			},
		},
	},
}
