return {
	armfort = {
		acceleration = 0,
		blocking = true,
		brakerate = 0,
		buildangle = 0,
		buildcostenergy = 1063,
		buildcostmetal = 39,
		buildinggrounddecaltype = "armfort_aoplane.dds",
		buildpic = "ARMFORT.DDS",
		buildtime = 1065,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",
		corpse = "FORTIFICATION",
		description = "Fortification Wall",
		footprintx = 2,
		footprintz = 2,
		hidedamage = true,
		idleautoheal = 0,
		levelground = false,
		maxdamage = 8000,
		maxslope = 24,
		maxwaterdepth = 0,
		name = "Ston",
		objectname = "ARMFORT.s3o",
		repairable = false,
		seismicsignature = 0,
		sightdistance = 1,
		usebuildinggrounddecal = true,
		yardmap = "ffff",
		customparams = {
			faction = "arm",
		},
		featuredefs = {
			fortification = {
				autoreclaimable = 0,
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -3 0",
				collisionvolumescales = "32 50 32",
				collisionvolumetest = 1,
				collisionvolumetype = "CylY",
				damage = 8000,
				description = "Fortification Wall",
				featuredead = "RockTeethx",
				featurereclamate = "smudge01",
				footprintx = 2,
				footprintz = 2,
				height = 55,
				hitdensity = 100,
				metal = 15,
				object = "armfort.s3o",
				reclaimable = true,
				reclaimtime = 800,
				seqnamereclamate = "tree1reclamate",
				world = "allworld",
			},
			rockteethx = {
				animating = 0,
				animtrans = 0,
				blocking = true,
				category = "heaps",
				damage = 3000,
				description = "Rubble",
				footprintx = 2,
				footprintz = 2,
				height = 20,
				hitdensity = 100,
				metal = 7,
				object = "arm2X2A",
				reclaimable = true,
				resurrectable = 0,
				shadtrans = 1,
				world = "greenworld",
			},
		},
	},
}
