return {
	armsl = {
		acceleration = 0.15,
		brakerate = 0.5,
		buildcostenergy = 6497,
		buildcostmetal = 367,
		buildpic = "ARMSL.DDS",
		buildtime = 15289,
		canfly = true,
		canmove = true,
		category = "ALL NOTSUB VTOL NOWEAPON NOTHOVER",
		collide = false,
		cruisealt = 150,
		description = "Heavy Transport",
		energymake = 3,
		energyuse = 16,
		explodeas = "SMALL_UNITEX",
		footprintx = 4,
		footprintz = 4,
		hoverattack = true,
		icontype = "air",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 1800,
		maxslope = 10,
		maxvelocity = 7,
		maxwaterdepth = 0,
		name = "Seahook",
		objectname = "ARMSL.s3o",
		releaseheld = true,
		seismicsignature = 0,
		selfdestructas = "SMALL_UNIT",
		sightdistance = 260,
		transportcapacity = 30,
		transportsize = 15,
		turninplaceanglelimit = 360,
		turnrate = 380,
		upright = true,
		customparams = {
			faction = "core",
			normalmaps = "yes",
			normaltex = "unittextures/Core_normal.dds",
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "vtolcrmv",
			},
			select = {
				[1] = "vtolcrac",
			},
		},
	},
}
