return {
	freefusion = {
		acceleration = 0,
		activatewhenbuilt = true,
		brakerate = 0,
		buildangle = 4096,
		buildcostenergy = 50,
		buildcostmetal = 40,
		buildpic = "FREEFUSION.DDS",
		buildtime = 800,
		category = "ALL NOTLAND NOTSUB NOWEAPON NOTSHIP NOTAIR NOTHOVER SURFACE",

		corpse = "FREE_FUSION_DEAD",
		description = "Produces plenty of energy",
		energymake = 850,
		energystorage = 150,
		explodeas = "FUSIONX_BLAST",
		footprintx = 5,
		footprintz = 5,
		icontype = "building",
		idleautoheal = 5,
		idletime = 1800,
		maxdamage = 500,
		maxslope = 20,
		maxwaterdepth = 0,
		name = "Free Fusion Reactor",
		objectname = "freefusion.s3o",
		seismicsignature = 0,
		selfdestructas = "FUSIONX_BLAST",
		sightdistance = 250,
		yardmap = "ooooooooooooooooooooooooo",

		featuredefs = {
			free_fusion_dead = {
				blocking = true,
				category = "corpses",
				damage = 2500,
				description = "Free Fusion Reactor Wreckage",
				energy = 0,
				footprintx = 5,
				footprintz = 5,
				height = 20,
				hitdensity = 100,
				metal = 3300,
				object = "freefusion_dead.s3o",
				reclaimable = true,
			},
		},
	},
}
