return {
	teleport = {
		acceleration = 0,
		activatewhenbuilt = true,
		autoheal = 0,
		brakerate = 0,
		buildcostenergy = 1,
		buildcostmetal = 1,
		builder = false,
		buildtime = 1,
		category = "NOTAIR NOTSUB NOTSHIP NOTHOVER ALL SURFACE",
		description = "Teleport Device",
		explodeas = "",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 0,
		idletime = 0,
		mass = 100,
		maxdamage = 1,
		maxvelocity = 0,
		name = "teleport",
		noautofire = false,
		objectname = "teleport.s3o",
		radardistance = 1,
		selfdestructas = "",
		sightdistance = 50,
		turninplaceanglelimit = 140,
		turninplacespeedlimit = 0,
		turnrate = 0,
		upright = false,
		waterline = 0,
		workertime = 0,
		customparams = {
			faction = "none",
		},
		featuredefs = {},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:sky_enterance",
				[2] = "custom:teleport_beam",
			},
		},
		weapondefs = {
			teleport = {
				accuracy = 1,
				areaofeffect = 100,
				avoidfriendly = false,
				beamttl = 10,
				craterboost = 0,
				cratermult = 0,
				duration = 10.6,
				explosiongenerator = "custom:none",
				impulseboost = 0.123,
				impulsefactor = 0.123,
				intensity = 25,
				name = "Lightning Transport Beam",
				noselfdamage = true,
				range = 3000,
				reloadtime = 0.001,
				rgbcolor = "0.6 0.6 0.9",
				soundhitdry = "maghit",
				soundstart = "krypto",
				texture1 = "strike",
				thickness = 40,
				tolerance = 6,
				turret = true,
				weapontype = "LightningCannon",
				weaponvelocity = 560,
				damage = {
					default = 0,
				},
			},
		},
		weapons = {
			[1] = {
				def = "TELEPORT",
			},
		},
	},
}
